### ISSUE TITLE
Integrate into nextcloud 16 viewer

### ISSUE THREAD

**Issue by skjnldsv** [v1r0x/files_3d#4]
Hello!
16 will ship a new viewer wich  aim to unify the file various views.
Please have a look at the conversation about the cameraraw app integration here: https://github.com/nextcloud/viewer/issues/25

I think it would be very nice to have your awesome app in the same unified view as this! :wink:

**Comment by v1r0x** [comment]
Thanks for the reminder, it's already on my todo list :wink: 
Is it possible to bind the viewer to a specific file suffix instead of mime type? 3d files often seem to not have the mime type they should have...

**Comment by skjnldsv** [comment]
@v1r0x Currently no, as this is not bound to the viewer but to the way the filelist handle actions. :disappointed: 
https://github.com/nextcloud/server/blob/fix/settings/use-components-multiselect/apps/files/js/fileactions.js#L212

**Comment by v1r0x** [comment]
I started porting :tada: (see my fork of the viewer repo)
Due to the missing binding to file suffix it is very limited and the most common `obj` (official mimetype is `text/plain`) and `fbx` ("official" mimetype is `application/octet-stream`) formats are not supported.

The port is untested, so try on your own risk :skull_and_crossbones: :laughing:

**Comment by skjnldsv** [comment]
@v1r0x you don't need to fork the viewer, right?
You did it just to test?

I'll take a look :)

**Comment by v1r0x** [comment]
Yes, I could have created a branch instead of a fork, but didn't want to "spam" the repo :wink: 

Edit: The fork won't work, I forgot to include the 3d lib :sweat_smile:

**Comment by skjnldsv** [comment]
@v1r0x No, I meant that the idea is that external apps register their own views. We should not add the 3d viewer in the main viewer repo, but from this app :)

EDIT: small comment https://github.com/v1r0x/viewer/commit/75b26ece30cbc5d0a656ed6ddeb7508fed7cb17d#r33014373 :wink:

**Comment by v1r0x** [comment]
> @v1r0x No, I meant that the idea is that external apps register their own views. We should not add the 3d viewer in the main viewer repo, but from this app :)

Sounds reasonable :grin: I'll merge it back into this repo after I fixed/decided how to import THREE.

**Comment by v1r0x** [comment]
@skjnldsv I started working on the port on the `viewer` branch. File format is still a problem, because 3d files don't have a correct mime-type (even formats with a specified mime-type have `text/plain`...even after using their official file converters).
Beside that I can't get it to work. I copied the webpack stuff from another project of mine and compiling works. But when I activate the app and load the files app, I get a CSP error, because my component is loaded using `eval()`. Did I miss something or is something wrong?

**Comment by skjnldsv** [comment]
@v1r0x again, you cannot use eval on nextcloud, this is disabled for safety reasons :)
You can check the webpack conf on the viewer repo, they works fine.
If you want to stay on your webpack files, you need to check your source-map config, sometimes they use eval here. You need to compare with the viewer repo (ot contacts, or mail... :wink: )

**Comment by v1r0x** [comment]
@skjnldsv I switched to the webpack config of the viewer and now it kinda works. Thanks for your help!
Only problems I get are
- same "Handler already registered" as already mentioned in the viewer repo. 
- `vue-threejs` doesn't seem to work with that webpack config or whatsoever.

**Comment by skjnldsv** [comment]
For the `Handler already registered` any more input on the log?
Do you have a branch I can check? :)

**Comment by v1r0x** [comment]
Nothing in the logs.
Yes, you can checkout the `viewer` branch. But you have to uncomment Lines 34-36 in `Files3d.vue` to activate vue-threejs.

**Comment by skjnldsv** [comment]
Okay, it is working on my side.
You can ignore the warning about already registered handler, I'll fix it on viewer :)

After setting up the mimetype mapping and running `occ maintenance:mimetype:update-db` it works fine! (I see the alerts)

Btw you have a typo in your readme `confog` and you should probably add the full occ command to be more precise, otherwise it require ppl to go check the docs ;)

**Comment by skjnldsv** [comment]
Also, on a side note, the 3d files should not be in the media group :wink:

**Comment by v1r0x** [comment]
Yes, alerts are working, but only if you don't include lines 34-36 in `Files3d.vue`. When included, I get `TypeError: plugin is undefined` and alerts are no longer working.

Thanks for the info! I didn't want to add the command, so I don't have to update it everytime the doc changes :wink: 

Can I pick my own group or any suggestions? :)

**Comment by skjnldsv** [comment]
`3d` ?
Feels simple enough :)

Yep, I cannot get vuethree-js to work. Let's fallback to pure three.js?

**Comment by e-alfred** [comment]
It would be great to have this integrated into the official viewer. Are basic controls (like close, next, previous etc) already available for all supported filetypes in the official file viewer (because they are missing in the this app)?

**Comment by skjnldsv** [comment]
Hey there! :)
Any news?

**Comment by v1r0x** [comment]
Unfortunately not...Problem is that "all" (at least all I tried) 3d files do not set the correct mime-type. Most of them are either `text/plain` or `application/octet-stream`. Thus it's not possible to add a 3d viewer as an action.

If viewer could add actions to file suffix instead (or in addition) this would be awesome! :)

**Comment by skjnldsv** [comment]
> If viewer could add actions to file suffix instead (or in addition) this would be awesome! :)

What does that means?  :)

**Comment by v1r0x** [comment]
`add action = registerHandler()` :wink: 

The `registerHandler()` method of viewer only supports a `mimes: []`property. This doesn't work with 3d files, because several formats have no specific mimetype or other 3d softwares do not set the correct mimetype.
Thus, in another project, I use the file suffix (`.obj`, `.fbx`, ...) to init the correct file loader. Since viewer does not support a `suffix: []` property, this app is not functional.

**Comment by skjnldsv** [comment]
Ah yes, sorry! I did not understand what you meant by suffix.
File extension is more appropriate there :p

**Comment by v1r0x** [comment]
Sorry for the confusion! :D It was the first word that came to my mind :sweat_smile:

**Comment by v1r0x** [comment]
hey @skjnldsv 
are there any plans to support a `extensions: []` property instead of `mimes: []` in the future? Without I don't see a proper solution to support 3d files in nc.
If there is another solution to support files with missing or wrong mimetypes, I'm happy to implement that :)

**Comment by skjnldsv** [comment]
@v1r0x Isn't using mimetype enough? Like you do here?
https://github.com/v1r0x/files_3d/blob/75739d9341ae9ae1986d951fe8a6ac34c7d9b9ac/js/loader.js#L194

Because we're using the mime given by the files app, so it should still match now, right?

**Comment by v1r0x** [comment]
Unfortunately not. As you can see in `loader.js` I have added two dummy mimetypes for `.obj` and `.fbx` files, because they don't have a mimetype assigned. `.obj` is simply `text/plain`.
For some of the other 3d file formats there is a mimetype but most 3d software does not use them, so there is no chance to identify 3d files by their mimetype.
And to set the dummy mimetypes users/admins have to add mimetypemapping to their nc instance. Which only works for new uploads? Or is there a occ command to trigger a rescan of all files?

Edit: 

> Because we're using the mime given by the files app, so it should still match now, right?

Yes, same problem exists with files app. There I had the same problems.

**Comment by skjnldsv** [comment]
> Yes, same problem exists with files app. There I had the same problems.

that explains :)
Thus it will require it to work with the files app first I guess?

**Comment by v1r0x** [comment]
I thought viewer should replace all the `files_*` apps in the long run? But I'm happy with both, a solution in files app and in viewer :)

**Comment by skjnldsv** [comment]
Well,t he main files app is here to register the default file action for specific mimetypes :)
The viewer is registering those as well :thinking:

**Comment by v1r0x** [comment]
If both systems (files_* apps and viewer components) should exist in the future, it would be good if both systems could support file actions based on file extensions. Should I open issues in both repos to discuss it or what should I/we do? I'm confused what's the plan now :sweat_smile:

**Comment by skjnldsv** [comment]
> it would be good if both systems could support file actions based on file extensions. Should I open issues in both repos to discuss it or what should I/we do? I'm confused what's the plan now

luckily we had a talk about the future implementation of a fileAction api last week, I'll open an issue soon :)

**Comment by v1r0x** [comment]
sounds good! :) thank you

**Comment by awesome-manuel** [comment]
I don't get the problem with mimetype vs file extension, since mimetypes are never stored inside a file. Applications need to figure out the mimetype depending on the first bytes in the file or the file extension. Nextcloud has a map of extensions to mimetypes and it seems an app can add more mappings, see https://github.com/jhass/nextcloud-keeweb/pull/124/files.
See also https://docs.nextcloud.com/server/13.0.0/developer_manual/api/OC/Files/Type/Detection.html

The official mimetypes can be found here: https://www.iana.org/assignments/media-types/media-types.xhtml#model

**Comment by v1r0x** [comment]
The problem is, that most 3d files have no mimetype set (doesn't matter if it's the first bytes or actually "stored" in a file). The next thing is that I couldn't get mimetypes for all 3d file types. E.g. fbx doesn't have one at all. For obj I found several.

I didn't know an app can set it's own mappings. Thanks for that info.

But in general it feels weird to add a mapping on backend-side for non-existing mime types (in a pure js/frontend app) instead of using the file extension. And the file extension is easier to get than the mime type :wink:

**Comment by awesome-manuel** [comment]
I think you still have some misconception about mimetypes. Also for images like JPEG it's up to Nextcloud to figure out the right mimetype (by looking at the content or using the file extension). If Nextcloud does not know about a particular mimetype (like those for 3D models) it cannot do this job and you have to give it a hint how to figure this out.

**Comment by v1r0x** [comment]
No, I'm pretty sure I know how it works.

Mimetypes and file extension are (completely) unrelated. And it's not only Nextcloud which doesn't know about the 3d file mimetypes, there are **none**. A fbx file **will never** have a valid/standardized mimetype. Thus I have to come up with one to be able to make it work in Nextcloud. For the current (alpha) version in the appstore I did exactly this. I have added mapping from fbx to a `application/fbx-dummy` or something like that. And that's a crappy solution, but the only one that works in NC. For several reasons I don't want to do this again, thus I was asking for file extension support. Which is also much easier to handle.

**Comment by awesome-manuel** [comment]
For everything related to the web mimetypes are the way to go with. You often get resources via an URL where you don't have file names or file extensions at all but the webserver provides a mimetype in the HTTP header.
The file format fbx is vendor specific and owned by Autodesk. They are free to file a registration request with IANA to get an offical mimetype. While this is not the case you are free to use or own, prefixed with "vnd." or "x-" (obsolete), but not postfixed with "-dummy". See https://en.wikipedia.org/wiki/Media_type#Vendor_tree

**Comment by v1r0x** [comment]
@skjnldsv thanks to @awesome-manuel the mime stuff works, but now I'm stuck...again.

In the viewer repo the readme says
> Create a vue component which use the `path` and `mime` props (they will be automatically passed by the viewer)

but only the `mime`prop is set/available.

My component also gets mounted several times. Sometimes twice, sometimes three times :confused: 
This behaviour happens on the viewer branch. Any help is much appreciated!

**Comment by skjnldsv** [comment]
Do yo uhave some code or pull request to show me? :)

**Comment by v1r0x** [comment]
> Do yo uhave some code or pull request to show me? :)

you can checkout the viewer branch or #10 if you prefer a PR ;)

When you open a supported file (fbx, obj, dae, gltf), you should see several logs with mimetypes and undefined (see `path` in line 82 in src/components/Files3d.vue) popping up in the console.

And another question:
When should the active watcher if statement be true? On my testing instance the watcher wasn't even called.

**Comment by skjnldsv** [comment]
Added a few comments :)
Great work so far, code looks nice!
