### ISSUE TITLE
CSP issues, doesn't load

### ISSUE THREAD

**Issue by PVince81** [v1r0x/files_3d#53]
### Steps

1. Setup Nextcloud 23.0.2
2. `occ app:enable files_3d`
3. Upload a GLTF file
4. Try opening it

### Expected result
3d model appears

### Actual result
The viewer app appears and the JS console shows CSP errors about WebGL:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/277525/155333453-968a6975-dc70-41bd-bb77-553806c3d4e2.png">

### Versions
Tested with the app store version and also with the master branch after compiling.

**Comment by PVince81** [comment]
you might need to adjust the CSP policies, see https://github.com/nextcloud/spreed/blob/v12.0.0/lib/Controller/PageController.php#L262 for an example how to set some

**Comment by v1r0x** [comment]
Thanks for your issue!

I can not reproduce that error on my instance. But from what I see on your screenshot, this should be fixed by adding CSP policy for the connect domain with `$csp->addAllowedConnectDomain("'self'");`. But as I don't have a controller set up, I'm not sure how this can be done in my viewer plugin?
cc @skjnldsv can you help me out again? :sweat_smile:

**Comment by skjnldsv** [comment]
No idea really, I guess you can adjust the connect-src csp policy the same way?
Really not my expertise :see_no_evil:

**Comment by PVince81** [comment]
PR here: https://github.com/v1r0x/files_3d/pull/57

**Comment by PVince81** [comment]
the CSP issue I had was due to a conflict of policies from other apps
this general issue will be resolved in Nextcloud 25: https://github.com/nextcloud/server/pull/32113

now with https://github.com/v1r0x/files_3d/pull/57 in place the issue will not appear any more for this app
