### ISSUE TITLE
Awesome! Nextcloud 18 support

### ISSUE THREAD

**Issue by almare** [v1r0x/files_3d#7]
This is exactly what I need. Do you think it's possible to support nextcloud 18?
Thank you for your work!!

**Comment by v1r0x** [comment]
Hey @almare 
thanks for the kind words! Unfortunately, this is app is currently unmaintained.

The problem is that most of 3d files do not set a (correct) mime-type and thus are not supported. And some file types do not have a mime-type at all. The new (since nc 16) viewer plugin of nc only allows to register mime-types, but not file extensions (see #4) to register an external app to show the file content.
As long as there is no solution to this, I won't put more work into this, because the current workaround (for pre nc16) is not very stable but error prone. Sorry!

**Comment by v1r0x** [comment]
hey @almare 

quick update: thanks to @awesome-manuel it is now easier to register mimetypes. I'm currently working on a new release, but it depends on a fix in the nextcloud viewer repo, which is shipped with nc 19.
I hope I can release a new version together with nc 19 :)

**Comment by almare** [comment]
Oh, great info! Thank you for your feedback in this topic. Hopefully you can handle all the problems :-)

**Comment by d3xma** [comment]
@v1r0x this would be highly appreciated!

**Comment by cwbsl** [comment]
Is there any estimate on when this awesome app will be working again with nc 19?

**Comment by v1r0x** [comment]
Thank you all for your interest 😊
I try to find some time for it in the coming days. Sorry for the delay.

**Comment by v1r0x** [comment]
A new release for NC 19 is ready! :tada: It's not yet in the appstore, but you can use the release here from github
